
depos_para_informes = (0,1,2,3,4,5,6,7,8,9,11,12,14,15,198)

########################################################################################################################################
###########                                          TABLAS SERVER MSSQL                                                   #############
########################################################################################################################################

db1.define_table('articulo',	
Field('codigo','id'),
Field('descripcion_1','string'),
Field('descripcion_2','string'),
Field('descripcion_3','string'),
Field('descripcion_4','string'),
Field('descripcion_5','string'),
Field('codigo_barra','integer'),
Field('codigo_sinonimo','string'),
Field('unidad_medida','string'),
Field('medida','string'),
Field('cantidad_unidades','float'),
Field('peso','float'),
Field('precio_1','float'),
Field('precio_2','float'),
Field('precio_3','float'),
Field('precio_4','float'),
Field('precio_costo','float'),
Field('precio_sugerido','float'),
Field('formula','float'),
Field('descuento','float'),
Field('deducible_1','float'),
Field('deducible_2','float'),
Field('deducible_3','float'),
Field('deducible_4','float'),
Field('marca','integer'),
Field('rubro','float'),
Field('subrubro','float'),
Field('comentarios','string'),
Field('calificacion','string'),
Field('factura_por_total','string'),
Field('oferta','string'),
Field('grupo','string'),
Field('alicuota_iva1','float'),
Field('alicuota_iva2','float'),
Field('tipo_iva','string'),
Field('utilidad_1','float'),
Field('utilidad_2','float'),
Field('utilidad_3','float'),
Field('utilidad_4','float'),
Field('cuenta_compras','string'),
Field('cuenta_ventas','string'),
Field('comision','float'),
Field('linea','float'),
Field('color','string'),
Field('cuenta_vta_anti','string'),
Field('cuenta_com_anti','string'),
Field('precio_fabrica','float'),
Field('alicuota_ib_may','float'),
Field('alicuota_ib_min','float'),
Field('estado','string'),
Field('porc_viajante','float'),
Field('tarima','float'),
Field('proveedor','float'),
Field('fecha_ult_compra','datetime'),
Field('deposito','float'),
Field('capacidad_almacenaje','float'),
Field('precio_calculo','float'),
Field('usuario','string'),
Field('fecha_hora','datetime'),
Field('abm','string'),
Field('redondea','string'),
Field('tipo_medida','float'),
Field('porcentaje','string'),
Field('punto_pedido','float'),
Field('nivel_minimo','float'),
Field('flete','float'),
Field('cantidad_minima','float'),
Field('cantidad_maxima','float'),
Field('facturacion_directa','string'),
Field('cuenta_cosecha','string'),
Field('impuesto_no_computable','float'),
Field('largo','float'),
Field('ancho','float'),
Field('descuento_1','float'),
Field('descuento_2','float'),
Field('descuento_3','float'),
Field('descuento_4','float'),
Field('mano_obra','float'),
Field('materia_prima','float'),
Field('otros_costos','float'),
Field('financiacion','float'),
Field('fecha_modificacion','datetime'),
Field('precio_dolar','float'),
Field('operador_unidades','string'),
Field('numero_maximo','string'),
Field('tipo_codigo_barra','string'),
Field('stock','string'),
Field('moneda','float'),
Field('codigo_envase','float'),
Field('porc_impuesto','float'),
Field('pack','string'),
Field('cuenta_y_orden','string'),
Field('precio_costo_pres','float'),
Field('moneda_pres','float'),
Field('frecuencia_reparto','string'),
Field('cta_vta_fac_rem','string'),
Field('cta_cpa_fac_rem','string'),
Field('frecuencia','string'),
Field('serie_defecto','string'),
Field('modelo','string'),
Field('codigo_comision','float'),
Field('cta_cpa_dico','string'),
Field('cta_costo_vta','string'),
Field('compra_anticipada','string'),
Field('incr_decr','float'),
Field('codigo_objeto_costo','string'),
Field('cantidad_referencia','float'),
Field('unidad_referencia','float'),
Field('controla_entrega','string'),
Field('cta_cpa_tercero','string'),
Field('cta_vta_tercero','string'),
Field('codigo_facturacion','string'),
Field('desc_atrib_1','string'),
Field('desc_atrib_2','string'),
Field('desc_atrib_3','string'),
Field('desc_atrib_4','string'),
Field('desc_atrib_5','string'),
Field('VOLUMEN','float'),
Field('principio_activo','string'),
Field('toxicidad','string'),
Field('garantia_extendida','string'),
Field('resultado_tenencia','string'),
Field('concentracion','string'),
Field('CLASIFICACION_FISCAL','string'),
Field('CODIGO_CFOP','string'),
Field('PESO_TOTAL','float'),
Field('CODIGO_CLASIFICACION_FINAN','float'),
Field('lista','string'),
Field('codigo_dgi','float'),
Field('porc_bon_dcto1','float'),
Field('costo_1','float'),
Field('porc_bon_dcto2','float'),
Field('costo_2','float'),
Field('porc_bon_dcto3','float'),
Field('costo_3','float'),
Field('porc_bon_dcto4','float'),
Field('relacion','float'),
Field('permite_dcto','string'),
Field('combo','string'),
Field('COSEGURO','string'),
Field('codigo_rubro_gastos','float'),
Field('meses_gtia_fabrica','float'),
Field('fecha_alta','datetime'),
Field('discontinuo','string'),
Field('cuenta_ventas_fac_interna','string'),
Field('alicuota_iva1_ventas','float'),
Field('codigo_nomenclador_mercosur','string'),
Field('precio_visible','string'),
Field('cta_cpa_dif_prec','string'),
Field('codigo_imagen','float'),
Field('cta_cpa_fac_rem_cyo','string'),
Field('cta_vta_fac_rem_cyo','string'),
Field('cta_costo_vta_cyo','string'),
Field('cta_mercaderia_terc','string'),
Field('fecha_hora_creacion','datetime'),
Field('zona_deposito','string'),
Field('estado_web','string'),
Field('desc_larga','string'),
Field('procod','string'),
Field('cta_consumo_propio','string'),
Field('solo_pedidos','string'),
Field('cultivo','float'),
Field('division_maxima','float'),
Field('valor_dolar','float'),
Field('tiempo_carencia','float'),
Field('pesable','float'),
Field('descuento_tope','float'),
Field('metros3','float'),
Field('informa_senasa','string'),
Field('logica_qr','float'),
Field('paquete_pedido','float'),
Field('fecha_modificacion2','datetime'),
Field('inf_sedronar','string'),
Field('impuesto_interno','float'),
Field('sistema','string'),
Field('actividad_dgi_may','float'),
Field('actividad_dgi_min','float'),
Field('minutos_mano_obra','float'),
Field('codigo_barra2','float'),
Field('codigo_barra3','float'),
Field('obse_barra','string'),
Field('obse_barra2','string'),
Field('obse_barra3','string'),
Field('usuario_creacion','string'),
Field('host_creacion','string'),
Field('usuario_modificacion','string'),
Field('fecha_hora_modificacion','datetime'),
Field('host_modificacion','string'),
Field('nomenclador_arba','string'),
Field('metros2','float'),
Field('precio_estanio','float'),
Field('estanteria','string'),
Field('precio_pvp','float'),
Field('codigo_relacion','float'),
Field('alto','float'),
Field('id_categoria_sub1','float'),
Field('id_categoria_sub2','float'),
Field('bultos','float'),
migrate=False)

db1.define_table('ventas1',
Field('codigo','id'),
Field('letra','string'),
Field('sucursal','integer'),
Field('numero','integer'),
Field('orden','integer'),
Field('renglon','integer'),
Field('articulo','integer'),
# Field('descripcion','string'),
Field('precio','float'),
# Field('precio_sugerido','float'),
# Field('unidades','float'),
Field('cantidad','float'),
# Field('descuento_reng1','float'),
# Field('descuento_reng2','float'),
# Field('bonificacion_reng1','float'),
Field('deposito','integer'),
# Field('entregador','float'),
Field('viajante','float'), ## VENDEDOR
# Field('zona','float'),
# Field('estado_stock','string'),
# Field('estado_cc','string'),
# Field('estado_pedidos','string'),
# Field('estado','string'),
Field('fecha','datetime'),
# Field('cuenta','float'),
# Field('calificacion','string'),
# Field('deducible','float'),
# Field('cantidad_devuelta','float'),
# Field('cantidad_entregada','float'),
# Field('cantidad_pagada','float'),
# Field('monto_devuelto','float'),
# Field('monto_entregado','float'),
# Field('monto_pagado','float'),
# Field('consignacion','string'),
# Field('codigo_postal','float'),
# Field('descuento_general','float'),
# Field('bonificacion_general','float'),
# Field('financiacion_general','float'),
Field('condicion_iva','string'),
# Field('iva1','float'),
# Field('iva2','float'),
# Field('retiro','string'),
# Field('venta_anticipada','string'),
# Field('cuenta_y_orden','string'),
# Field('fecha_vigencia','datetime'),
# Field('tipo_lista','float'),
Field('monto_facturado','float'), ## PRECIO POR CANTIDAD IVA INCLUIDO
# Field('cantidad_facturada','float'),
# Field('comision','float'),
# Field('fecha_hora','datetime'),
Field('operacion','string'), ## VENTAS:+, DEVOLUCIONES:-
# Field('cambio','string'),
# Field('nc_pendiente','string'),
# Field('precio_costo','float'),
# Field('serie','string'),
# Field('plan_canje','string'),
# Field('flete','float'),
# Field('muestra','string'),
# Field('fideicomiso','string'),
# Field('codigo_sinonimo','string'),
Field('dolar_remito','float'),
# Field('zona_origen','float'),
# Field('zona_destino','float'),
# Field('tarifa_flete','float'),
# Field('deposito_destino','float'),
# Field('codigo_objeto_costo','string'),
# Field('cantidad_referencia','float'),
# Field('unidad_referencia','float'),
# Field('cantidad_bultos','float'),
# Field('gtia_ext','string'),
# Field('campania','float'),
# Field('SUCURSAL_OT','float'),
# Field('NUMERO_OT','float'),
# Field('acta','float'),
# Field('destino_producto','float'),
# Field('TIPO_TARIFA','float'),
# Field('IMPORTE_SEGURO','float'),
Field('total_item','float'), ## PRECIO POR CANTIDAD SIN IVA
# Field('cli_orden','float'),
# Field('suc_orden','float'),
# Field('num_orden','float'),
# Field('devolucion_cc','string'),
# Field('usuario_creacion','string'),
# Field('fecha_hora_creacion','datetime'),
# Field('host_creacion','string'),
# Field('usuario_modificacion','string'),
# Field('fecha_hora_modificacion','datetime'),
# Field('host_modificacion','string'),
# Field('tipo_empresa','float'),
# Field('descuento_general_2','float'),
# Field('entrega','float'),
# Field('numero_rem','float'),
# Field('fecha_rem','datetime'),
# Field('sucursal_rem','float'),
# Field('orden_corte','float'),
# Field('liquidacion','float'),
# Field('renta_liqui','float'),
# Field('porce_liqui','float'),
# Field('destino_merca','string'),
# Field('flete_a_cargo','string'),
# Field('articulo_cli','string'),
# Field('cod_despacho','string'),
# Field('pais_destino','float'),
# Field('cod_despacho_plaza','string'),
# Field('tipo_liquidacion','string'),
# Field('tipo_empresa_gen','float'),
# Field('operador_cuenta','float'),
# Field('despachado','string'),
# Field('fecha_despacho','datetime'),
# Field('oferta','string'),
# Field('recargo_reng1','float'),
# Field('recargo_reng2','float'),
# Field('unidad_medida','string'),
# Field('fabricacion_lote','datetime'),
# Field('vencimiento_lote','datetime'),
# Field('impuesto_vta','float'),
# Field('observaciones','string'),
# Field('precio_minimo','float'),
# Field('datosgia','string'),
#primarykey=['codigo','letra','sucursal','numero','orden','renglon'],
migrate=False)

db1.define_table('viajantes',
Field('codigo','id'),
Field('descripcion','string'),
# Field('direccion','string'),
# Field('porcentaje','float'),
# Field('codigo_postal','integer'),
# Field('telefono','string'),
# Field('origen','integer'),
# Field('numero_cuenta','integer'),
# Field('porcentaje_2','float'),
# Field('porcentaje_cobranza','float'),
# Field('divisiones_habilitadas','string'),
# Field('estado','string'),
# Field('usuario','string'),
# Field('fecha_hora','datetime'),
# Field('abm','string'),
# Field('permiso_autorizacion','string'),
# Field('clave_autorizacion','string'),
# Field('sector_contable','integer'),
migrate=False)

db1.define_table('stock',
	Field('deposito','integer',8),
	Field('articulo','integer',8),
	Field('stock_actual','integer',16),
	Field('stock_pendiente','integer',16),
	Field('stock_custodia','integer',16),
	Field('punto_pedido','integer',12),
	Field('nivel_minimo','integer',12),
	Field('cantidad_apedir','integer',12),
	Field('serie','string',20),
	Field('stock_unidades','integer',14),
	Field('codigo_sinonimo','string',40),
	Field('fecha_hora','datetime'),
	migrate=False)

db1.define_table('marcas',
	Field('codigo','id'),
	Field('descripcion','string',150),
	Field('salto_pagina','string',1),
	Field('color','string',9),
	Field('indice','integer',4),
	Field('reducida','string',6),
	Field('fecha_modificacion','datetime'),
	Field('cuenta','integer',8),
	Field('dias_max_reparacion','integer',8),
	Field('sinonimo','integer',8),
	migrate=False)

db1.define_table('compras1',	
	Field('codigo','id'),
	Field('letra','string',4),
	Field('sucursal','integer'),
	Field('numero','integer'),
	Field('orden','integer'),
	Field('renglon','integer'),
	Field('articulo','integer'),
	Field('descripcion','string',160),
	Field('precio','float'),
#	Field('precio_sugerido','float'),
	Field('unidades','float'),
	Field('cantidad','float'),
	Field('descuento_reng1','float'),
	Field('descuento_reng2','float'),
#	Field('bonificacion_reng1','float'),
	Field('deposito','integer'),
#	Field('entregador','integer'),
	Field('viajante','integer'),
	Field('zona','integer'),
	Field('estado_stock','string',1	),
	Field('estado_cc','string',	2),
	Field('estado_pedidos','string',1),
	Field('estado','string',1),
	Field('fecha','datetime'),
	Field('cuenta','integer'),
	Field('calificacion','string',3	),
#	Field('deducible','float'),
	Field('cantidad_devuelta','float'),
	Field('cantidad_entregada','float'),
	Field('cantidad_pagada','float'),
	Field('monto_devuelto','float'),
	Field('monto_entregado','float'),
	Field('monto_pagado','float'),
	Field('consignacion','string',2),
#	Field('codigo_postal','integer'),
	Field('descuento_general','float'),
	Field('bonificacion_general','float'),
	Field('financiacion_general','float'),
	Field('condicion_iva','string',1),
	Field('iva1','float'),
	Field('iva2','float'),
#	Field('retiro','string',1),
	Field('venta_anticipada','string',1	),
	Field('cuenta_y_orden','string',1),
#	Field('fecha_vigencia','datetime'),
#	Field('tipo_lista','integer'),
	Field('monto_facturado','float'),
	Field('cantidad_facturada','float'),
	Field('comision','float'),
	Field('fecha_hora','datetime'),
	Field('operacion','string',1),
#	Field('cambio','string',1),
#	Field('nc_pendiente','string',1),
#	Field('precio_costo','float'),
	Field('serie','string',20),
#	Field('plan_canje',#'string',1),
	Field('flete','integer'),
	Field('muestra','str#ing',20	),
#	Field('fideicomiso','string',1),
	Field('codigo_sinonimo','string',40),
	Field('dolar_remito','float'),
	Field('zona_origen','integer'),
	Field('zona_destino','integer'),
	Field('tarifa_flete','float'),
	Field('deposito_destino','integer'),
	Field('codigo_objeto_costo','string',10),
	Field('cantidad_referencia','float'),
	Field('unidad_referencia','float'),
#	Field('cantidad_bultos','float'),
#	Field('gtia_ext','string',1),
#	Field('campania','integer'),
#	Field('SUCURSAL_OT','integer'),
#	Field('NUMERO_OT','integer'),
#	Field('acta','integer'),
	Field('destino_producto','integer'),
#	Field('TIPO_TARIFA','integer'),
#	Field('IMPORTE_SEGURO','float'),
#	Field('total_item','float'),
#	Field('cli_orden','integer'),
#	Field('suc_orden','integer'),
#	Field('num_orden','integer'),
#	Field('devolucion_cc','string',1),
	Field('usuario_creacion','string',20),
	Field('fecha_hora_creacion','datetime'),
	Field('host_creacion','string',50),
	Field('usuario_modificacion','string',20),
	Field('fecha_hora_modificacion','datetime'),
	Field('host_modificacion','string',50),
#	Field('tipo_empresa','integer'),
#	Field('descuento_general_2','float'),
#	Field('entrega','integer'),
#	Field('numero_rem','integer'),
#	Field('fecha_rem','datetime'),
#	Field('sucursal_rem','float'),
	Field('orden_corte','float'),
#	Field('liquidacion','float'),
#	Field('renta_liqui','float'),
#	Field('porce_liqui','float'),
#	Field('destino_merca','string',1),
#	Field('flete_a_cargo','string',1),
	Field('articulo_cli','string',15),
#	Field('cod_despacho','string',20),
#	Field('pais_destino','integer'),
	Field('cod_despacho_plaza','string',30),
#	Field('tipo_liquidacion','string',1),
#	Field('tipo_empresa_gen','integer'),
#	Field('operador_cuenta','integer'),
#	Field('despachado','string',1),
#	Field('fecha_despacho','datetime'),
#	Field('oferta','string',1),
#	Field('recargo_reng1','float'),
#	Field('recargo_reng2','float'),
	Field('unidad_medida','string',	15),
	Field('fabricacion_lote','datetime'),
	Field('vencimiento_lote','datetime'),
	Field('impuesto_vta','float'),
	Field('observaciones','string',100),
#	Field('precio_minimo','float'),
#	Field('datosgia','string',40),
	migrate=False)

db1.define_table('lineas',
	Field('codigo','id'),
	Field('descripcion','string',150),
	Field('color','string',9),
	Field('indice','int'),
	Field('reducida','string',6),
	migrate=False)

db1.define_table('rubros',
	Field('codigo','id'),
	Field('descripcion','string'),
	migrate=False)

db1.define_table('subrubro',
	Field('codigo','id'),
	Field('descripcion','string'),
	migrate=False)

db1.define_table('omicron_cer',
	Field('id','id'),
	Field('fecha','date'),
	Field('coef','float'),
	migrate=False)

db1.define_table('clientes',
	Field('numero','id'),
	Field('codigo_postal'),
	migrate=False)

db1.define_table('cod_postal',
	Field('codigo_postal','id'),
	Field('localidad'),
	migrate=False)



########################################################################################################################################
###########                                      FIN TABLAS SERVER MSSQL                                                   #############
########################################################################################################################################

##### VISTAS MSSQL #####

#stock consolidado, creado por Macrogestion
db1.define_table('web_stock',
	Field('deposito','integer'),
	Field('articulo','integer'),
	Field('stock_actual','integer'),
	Field('codigo_sinonimo','string'),
	migrate=False)

#tabla consolidada en vista mssql, creada por Lbovio
db1.define_table('omicron_compras1',	
	Field('articulo','integer'),
	Field('precio','float'),
	Field('cantidad','float'),
	Field('deposito','integer'),
	Field('fecha','datetime'),
	Field('monto_facturado','float'),
	Field('codigo','integer'),
	migrate=False)

# #tabla consolidada en vista mssql, creada por Lbovio
# db1.define_table('omicron_ventas1',
# Field('articulo','integer'),
# Field('precio','float'),
# Field('cantidad','float'),
# Field('deposito','integer'),
# Field('viajante','float'), ## VENDEDOR
# Field('fecha','datetime'),
# Field('monto_facturado','float'), ## PRECIO POR CANTIDAD IVA INCLUIDO
# Field('operacion','string'), ## VENTAS:+, DEVOLUCIONES:-
# Field('monto_facturado','float'),
# migrate=False)
# db1.omicron_ventas1.informes_cantidad = Field.Virtual(lambda row: float(row.omicron_ventas1.operacion+str(row.omicron_ventas1.cantidad)) if row.omicron_ventas1.codigo==3 else row.omicron_ventas1.cantidad)

db1.define_table('zonas',
	Field('codigo','id'),
	Field('descripcion'),
	migrate=False)


db1.define_table('proveedores',
	Field('numero','integer'),
	Field('denominacion','string'),
	primarykey=['numero'],
	migrate=False)